# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: recursive
       - uses: subosito/flutter-action@v2
         with:
           channel: 'beta'
       - run: flutter config --enable-web
       - run: flutter build web
       - uses: actions/upload-artifact@v3.1.0
         with:
           path: build/web
           name: 'web-binary'
  # Single deploy job since we're just deploying
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Download latest build
        uses: actions/download-artifact@v3.0.0
        with:
          name: 'web-binary'
          path: '/www/'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '/www/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
